name = "admin-worker"
main = "src/index.js"
compatibility_date = "2024-10-22"
node_compat = false

# Environment Variables (non-sensitive)
[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://bumsiku.kr"
JWT_EXPIRY = "7200"  # 2 hours in seconds

# D1 Database - 포스트, 댓글, 태그 데이터
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "YOUR_D1_DATABASE_ID"  # TODO: wrangler d1 create blog-db 후 ID 입력

# R2 Bucket - 이미지 파일 저장
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "blog-images"

# KV Namespace (선택) - 캐싱
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"  # TODO: wrangler kv:namespace create CACHE 후 ID 입력

# Secrets (설정 필요 - wrangler secret put)
# - JWT_SECRET: JWT 토큰 서명 키 (최소 32자)
# - ADMIN_USERNAME: 관리자 아이디
# - ADMIN_PASSWORD: 관리자 비밀번호 (bcrypt 해시 권장)
