name = "admin-worker"
main = "src/index.js"
compatibility_date = "2025-10-22"

# Environment Variables (non-sensitive)
[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "*"
JWT_EXPIRY = "7200"  # 2 hours in seconds

# D1 Database Bindings
[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "1da591ba-005a-41ef-86dd-f8755b06092d"

# R2 Bucket - 이미지 파일 저장
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "blog-images"

# Secrets (설정 필요 - wrangler secret put)
# - JWT_SECRET: JWT 토큰 서명 키 (최소 32자)
# - ADMIN_USERNAME: 관리자 아이디
# - ADMIN_PASSWORD: 관리자 비밀번호 (bcrypt 해시 권장)

# Observability Configuration
# Enables Cloudflare's built-in observability for production monitoring
[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true